model:
  base_learning_rate: 4.5e-06
  target: core.models.transformer.Transformer
  params:
    clip_model_name: "ViT-B/32"  # <--- [可選新增]
    # ckpt_path: ckpts/places256_transformer.ckpt
    cond_stage_key: segmentation
    attention_extent: mask
    mask_on_latent: true # set this to true during training only 
    transformer_config:
      target: core.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1025
        block_size: 257  # 257
        # n_layer: 40 # 24,40
        n_layer: 12 # 24,40
        # n_head: 16
        n_head: 8
        # n_embd: 1408
        n_embd: 768
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
        context_dim: 512 # <--- 確保這個存在且值正確

    first_stage_config:
      target: core.models.vqgan.VQModel
      params:
        ckpt_path: ckpts/places256_vqgan1024_BASE.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: core.modules.losses.DummyLoss
    cond_stage_config: "__is_unconditional__"

data:
  target: train.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4 # <--- 嘗試添加或調整這個值
    train:
      target: core.data.places365.Places
      params:
        dataroot: /home/carlos11/Downloads/code/SecondSemester/DLP/final/latent-code-inpainting/dataset/
        annotations_filepath: /home/carlos11/Downloads/code/SecondSemester/DLP/final/latent-code-inpainting/annotations/football_annotations_v1.csv # <--- 修改為您的 CSV 文件路徑
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'
    test:
      target: core.data.places365.Places
      params:
        dataroot: /home/carlos11/Downloads/code/SecondSemester/DLP/final/latent-code-inpainting/dataset/
        maskroot: /home/chenh/data/masks_val_512_eval
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'

lightning:
  trainer:
    # gpus: "0," # 您已經在命令列中通過 --gpus 0, 指定了，這裡可以不寫，或者保持一致
    # max_epochs: 20 # 您也在命令列中通過 --trainer.max_epochs 20 指定了
    accumulate_grad_batches: 4 # <--- 在這裡設置您想要的梯度累積步數
    # distributed_backend: ddp # train.py 中有預設邏輯，這裡不寫通常也可以
    # strategy: ddp # train.py 中有預設邏輯
    # accelerator: gpu # train.py 中有預設邏輯
    # devices: 1 # train.py 中有預設邏輯